version: 0.2

phases:
    install:
        commands:
            - echo Installing Node 12...
            - curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt install -y nodejs
    pre_build:
        commands:
            - echo Installing npm dependencies...
            - npm install
    build:
        commands:
            - echo Building started on `date` ...
            - npm run-script build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: build
